# Generated by Django 4.1.2 on 2022-10-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Логин')),
                ('anons', models.CharField(max_length=20, verbose_name='Пароль')),
                ('rating', models.CharField(max_length=30, verbose_name='Уровень доступа')),
            ],
        ),
    ]
