# Generated by Django 4.1.2 on 2022-10-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, verbose_name='Логин')),
                ('passwords', models.CharField(max_length=20, verbose_name='Пароль')),
                ('rating', models.CharField(max_length=30, verbose_name='Уровень доступа')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
